apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: platform
  source:
    repoURL: 'https://github.com/nolet7/ls-linkerd.git'
    targetRevision: 'main'
    path: 10-vault
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

