apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform stack (ESO + Vault store + Linkerd)
  sourceRepos:
    - 'https://github.com/nolet7/ls-linkerd.git'
    - 'https://helm.linkerd.io/stable'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
