apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: linkerd-identity-issuer
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tls_crt }}"
        tls.key: "{{ .tls_key }}"
  data:
    - secretKey: tls_crt
      remoteRef:
        key: linkerd/issuer
        property: tls.crt
    - secretKey: tls_key
      remoteRef:
        key: linkerd/issuer
        property: tls.key
