apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-trust-roots
  namespace: linkerd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: linkerd-trust-roots
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: linkerd/root
        property: ca.crt
